<a href="https://colab.research.google.com/github/greapis/jaeha-shim/blob/main/AI_Tensor_LS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math
import pandas as pd
import numpy as np


In [2]:
print(math.sqrt(16))
print(math.factorial(5))

print(np.array([1,2,3,4,5]))

4.0
120
[1 2 3 4 5]


In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
str = np.array(["apple", "banana", "cherry"])
print(str)

['apple' 'banana' 'cherry']


In [17]:
# 0과 1사이 균등분포 / 난수 1개 생성
rn1 = np.random.rand()

# 정규분포(평균 = 0, 표준편차 = 1)인 난수 50개 생성
rn2 = np.random.normal(loc=0, scale=1, size=50)

# 지정 범위 내 균등분포 난수 n개 생성
rn3 = np.random.uniform(0, 10, size=5)

In [18]:
print(rn1)
print(rn2)
print(rn3)

0.42581900736232237
[ 0.7466522  -0.10334999  0.08788665  0.0166809  -0.00672435 -1.63554451
  1.52729269 -0.3142366   0.16979676 -1.75499474 -1.69263593 -1.46995962
  0.69316219  1.00873732 -2.1821114  -0.57746178  0.12583269  1.17531466
 -0.44378267  1.81549272  0.07603231  0.49484839 -1.78430464  2.03265361
  1.47545752  0.1595744  -0.96552575  0.34679715  1.16506413 -0.0927009
  1.58913905 -0.76217539  0.5304049   1.23050914  0.72522312  0.71155186
 -0.69342914 -0.83498214  0.92612253  0.02788692 -0.65442106  0.1595482
 -0.13479936  1.16218667  0.40527165  0.01753806  0.6053016  -0.40633634
  0.65581095  1.58902134]
[2.49218154 9.93651454 4.02537209 6.4747431  5.06375507]
