<a href="https://colab.research.google.com/github/greapis/jaeha-shim/blob/main/AI_Tensor_LS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

import keras

from sklearn.model_selection import train_test_split

In [2]:
print(math.sqrt(16))
print(math.factorial(5))

print(np.array([1,2,3,4,5]))

4.0
120
[1 2 3 4 5]


In [3]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
str = np.array(["apple", "banana", "cherry"])
print(str)

['apple' 'banana' 'cherry']


In [5]:
# 0과 1사이 균등분포 / 난수 1개 생성
rn1 = np.random.rand()

# 정규분포(평균 = 0, 표준편차 = 1)인 난수 50개 생성
rn2 = np.random.normal(loc=0, scale=1, size=50)

# 지정 범위 내 균등분포 난수 n개 생성
rn3 = np.random.uniform(0, 10, size=5)

In [6]:
print(rn1)
print(rn2)
print(rn3)

0.37901313557494043
[ 0.63344747 -2.86212182 -0.55678509  2.03103192 -0.58334578 -0.98304432
  0.90198628  0.61264613 -0.45815194 -0.51661458  0.91410933  0.50892857
 -0.22460401 -0.29279171 -0.28972034  2.36956188 -2.10190801 -0.59659671
  1.51114439 -0.70093565  1.47584697  0.7670728  -0.21469012 -1.16014574
  1.01694393  1.12334041 -1.11481261 -0.29628337 -0.16985654 -0.48195453
 -0.60773717 -0.02980639 -0.26527499 -0.40206656 -1.27733766  0.39622401
  0.93536377  0.85625129 -1.10280253  0.32863999  0.71528719 -0.51785128
  2.08016154  0.12894892  0.41080168 -0.18929285 -0.86129156 -1.31993583
  1.40191357  0.19134848]
[9.20914819 5.80642787 6.46255122 9.28408593 8.35079623]


In [8]:
## line graph ##

x = [1,2,3,4,5]
y = [1,4,9,16,25]

plt.plot(x,y)

plt.title("Simple plot Chart")

plt.xlabel("x")
plt.ylabel("y")

# show the graph
plt.show()

In [18]:
# Panda - matplotlib Combination

# Dictionary Structure - (Key : Value) Structrue
data = {
    'Year': [2017, 2018, 2019],
    'Revenue': [25, 31, 35]
}

# DataFrame Structure
df = pd.DataFrame(data)

df.plot(
    x = 'Year',
    y = 'Revenue',
    kind = 'line',
    marker = 'o',
    color = 'Red',
    title = '3Y(2017~2019) Revenue'
)

plt.ylabel('Revenue Volume')
plt.show()